### ISSUE TITLE
Doesnt support yaml anchors

### ISSUE THREAD

**Issue by darren-west** [utilitywarehouse/gha-docker-uri-check#6]
### Description
If using YAML anchors this fails to work, looking at the source I think implementing this would require a different approach.

Example:
```yaml
images:
  - name: foo
    newTag: &imageTag stable 
  - name: bar
    newTag: *imageTag
```
